# Technische Einstellungen
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

# Das Register
title: Das Register
tagline: Touren und Aufzeichnungen
description: Touren, Wege und Aufzeichnungen.

url: https://gryphiusodenhobler.github.io
baseurl: /dasregister/

author:
  name: Das Register

# Theme
version: 2.1.0

github:
  repo: https://github.com/gryphiusodenhobler/dasregister
